#!/usr/bin/with-contenv bash

apt-get install --assume-yes jq

curl -L $(curl -s https://api.github.com/repos/filosottile/age/releases/latest | jq -r '.assets[] | select(.name|endswith("linux-amd64.tar.gz")).browser_download_url') | tar xvz -C /usr/local/bin --strip-components=1 age age-keygen

chown root:root /usr/local/bin/{age,age-keygen}
chmod 0755 /usr/local/bin/{age,age-keygen}
