#!/usr/bin/with-contenv bash

apt-get install --assume-yes bash-completion jq

curl -L $(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | jq -r '.assets[] | select(.name|endswith("linux_amd64")).browser_download_url') -o /usr/local/bin/yq
chown root:root /usr/local/bin/yq
chmod 0755 /usr/local/bin/yq

yq completion bash > /etc/bash_completion.d/yq
