#!/usr/bin/with-contenv bash

apt-get install --assume-yes bash-completion

curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
chown root:root /usr/local/bin/kubectl
chmod 0755 /usr/local/bin/kubectl

kubectl completion bash > /etc/bash_completion.d/kubectl
